name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees:
  - trfore
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Example code helps a lot!
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: input
    id: operating-system
    attributes:
      label: Operating System
      description: What operating system is the container running on?
      placeholder: "Example: Ubuntu 22.04 on WSL2"
    validations:
      required: true
  - type: dropdown
    id: container-manager
    attributes:
      label: Container Manager
      description: What container manager are you using?
      multiple: true
      options:
        - Docker
        - Kubernetes
        - Podman
        - Other
      default: 0
    validations:
      required: true
  - type: dropdown
    id: container-runtime
    attributes:
      label: Container Runtime
      description: What container runtime are you using?
      multiple: true
      options:
        - containerd
        - CRI-O
        - Docker
        - LXC
        - runC
        - Other
      default: 0
    validations:
      required: true
