name: Deploy to Docker Hub
on:
  workflow_call:
    inputs:
      PLATFORMS: # ex: linux/amd64
        required: true
        type: string
    secrets:
      USERNAME: # ex: ${{ secrets.DOCKERHUB_USERNAME }}
        required: true
      TOKEN: # ex: ${{ secrets.DOCKERHUB_TOKEN }}
        required: true

jobs:
  docker_hub:
    runs-on: ubuntu-latest
    steps:
      - name: Check out codebase
        uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          echo "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV
          echo "BASEOS_NAME=$(jq -r .baseos.name baseos_digest)" >> $GITHUB_ENV

          if [ -z $(jq -r .baseos.digest baseos_digest) ]; \
          then echo "BASEOS_DIGEST=""" >> $GITHUB_ENV; \
          else echo "BASEOS_DIGEST="@$(jq -r .baseos.digest baseos_digest)"" >> $GITHUB_ENV; \
          fi

      - name: Create Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ github.repository }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
          labels: |
            org.opencontainers.image.created=${{ env.BUILD_DATE }}
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.title=${{ github.repository }}
            org.opencontainers.image.base.digest=${{ env.BASEOS_DIGEST }}
            org.opencontainers.image.base.name=${{ env.BASEOS_NAME }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ inputs.PLATFORMS }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BASEOS_DIGEST=${{ env.BASEOS_DIGEST }}

      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.TOKEN }}
          short-description: ${{ github.event.repository.description }}
